#pragma warning disable CS0626, CS0824, CS0114, CS0108, CS0067, CS0649, CS0169, CS0414
namespace UnityEngine
{
    public struct Vector2 { public float x, y; public Vector2(float x, float y) { this.x = x; this.y = y; } public static Vector2 zero => default; public static Vector2 one => default; }
    public struct Vector3 { public float x, y, z; public Vector3(float x, float y, float z) { this.x = x; this.y = y; this.z = z; } public static Vector3 zero => default; }
    public struct Vector4 { public float x, y, z, w; }
    public struct Color { public float r, g, b, a; public Color(float r, float g, float b, float a = 1f) { this.r = r; this.g = g; this.b = b; this.a = a; } public static Color white => default; public static Color black => default; public static Color red => default; public static Color green => default; public static Color blue => default; public static Color yellow => default; public static Color gray => default; public static Color grey => default; public static Color clear => default; public static Color cyan => default; public static Color magenta => default; }
    public struct Color32 { public byte r, g, b, a; }
    public struct Rect { public float x, y, width, height; public Rect(float x, float y, float w, float h) { this.x = x; this.y = y; width = w; height = h; } public float xMin { get; set; } public float xMax { get; set; } public float yMin { get; set; } public float yMax { get; set; } public Vector2 center => default; public Vector2 size => default; public Vector2 position => default; public bool Contains(Vector2 p) => false; public static Rect zero => default; }
    public class Object { public string name; public static void Destroy(Object obj) { } public static void DestroyImmediate(Object obj) { } public int GetInstanceID() => 0; public override string ToString() => ""; public static implicit operator bool(Object o) => o != null; }
    public class Component : Object { public GameObject gameObject => null; public Transform transform => null; public T GetComponent<T>() => default; }
    public class Behaviour : Component { public bool enabled { get; set; } }
    public class MonoBehaviour : Behaviour { }
    public class GameObject : Object { public Transform transform => null; public T GetComponent<T>() => default; public T AddComponent<T>() where T : Component => default; public void SetActive(bool v) { } public bool activeSelf => false; }
    public class Transform : Component { public Vector3 position { get; set; } public Vector3 localPosition { get; set; } public Vector3 localScale { get; set; } }
    public class Texture : Object { public int width { get; set; } public int height { get; set; } }
    public class Texture2D : Texture { public Texture2D(int w, int h) { } public void Apply() { } public Color[] GetPixels() => null; public void SetPixels(Color[] c) { } public Color GetPixel(int x, int y) => default; public void SetPixel(int x, int y, Color c) { } public byte[] EncodeToPNG() => null; public void LoadImage(byte[] data) { } public static Texture2D blackTexture => null; public static Texture2D whiteTexture => null; }
    public class Material : Object { public Material(string s) { } public Material(Material m) { } public Color color { get; set; } public Texture mainTexture { get; set; } public void SetColor(string n, Color c) { } public void SetFloat(string n, float v) { } public void SetTexture(string n, Texture t) { } public Shader shader { get; set; } }
    public class Shader : Object { public static Shader Find(string n) => null; }
    public class Sprite : Object { public static Sprite Create(Texture2D t, Rect r, Vector2 p) => null; public Texture2D texture => null; public Rect rect => default; }
    public class Camera : Behaviour { public static Camera main => null; public static Camera current => null; public Vector3 ScreenToWorldPoint(Vector3 p) => default; }
    public class Renderer : Component { public Material material { get; set; } public Material[] materials { get; set; } public Material sharedMaterial { get; set; } }
    public class MeshRenderer : Renderer { }
    public class SpriteRenderer : Renderer { public Sprite sprite { get; set; } public Color color { get; set; } }
    public class RenderTexture : Texture { public RenderTexture(int w, int h, int d) { } public static RenderTexture active { get; set; } }
    public static class Mathf { public static float Abs(float v) => 0; public static int Abs(int v) => 0; public static float Max(float a, float b) => 0; public static float Min(float a, float b) => 0; public static int Max(int a, int b) => 0; public static int Min(int a, int b) => 0; public static float Clamp(float v, float min, float max) => 0; public static int Clamp(int v, int min, int max) => 0; public static float Clamp01(float v) => 0; public static float Lerp(float a, float b, float t) => 0; public static float InverseLerp(float a, float b, float v) => 0; public static float Floor(float v) => 0; public static int FloorToInt(float v) => 0; public static float Ceil(float v) => 0; public static int CeilToInt(float v) => 0; public static float Round(float v) => 0; public static int RoundToInt(float v) => 0; public static float Sqrt(float v) => 0; public static float Pow(float b, float e) => 0; public static float Log(float v) => 0; public static float Sin(float v) => 0; public static float Cos(float v) => 0; public static float PI => 3.14159f; public static float Infinity => float.PositiveInfinity; public static float NegativeInfinity => float.NegativeInfinity; public static float Epsilon => float.Epsilon; public static float Sign(float v) => 0; public static bool Approximately(float a, float b) => false; }
    public static class Debug { public static void Log(object m) { } public static void LogWarning(object m) { } public static void LogError(object m) { } }
    public static class Application { public static string dataPath => ""; public static string persistentDataPath => ""; public static RuntimePlatform platform => default; public static string version => ""; }
    public enum RuntimePlatform { WindowsPlayer, WindowsEditor, OSXPlayer, OSXEditor, LinuxPlayer, LinuxEditor, Android, IPhonePlayer }
    public enum TextAnchor { UpperLeft, UpperCenter, UpperRight, MiddleLeft, MiddleCenter, MiddleRight, LowerLeft, LowerCenter, LowerRight }
    public enum FontStyle { Normal, Bold, Italic, BoldAndItalic }
    public enum ScaleMode { StretchToFill, ScaleAndCrop, ScaleToFit }
    public enum KeyCode { None, Mouse0, Mouse1, Mouse2, LeftShift, RightShift, LeftControl, RightControl, LeftAlt, RightAlt, Return, Escape, Space, Tab, Delete, Backspace, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, Alpha0, Alpha1, Alpha2, Alpha3, Alpha4, Alpha5, Alpha6, Alpha7, Alpha8, Alpha9 }
    public enum EventType { MouseDown, MouseUp, MouseDrag, MouseMove, KeyDown, KeyUp, ScrollWheel, Repaint, Layout, Used, Ignore, ContextClick, DragUpdated, DragPerform, DragExited, ValidateCommand, ExecuteCommand }
    public class Event { public static Event current => null; public EventType type { get; set; } public KeyCode keyCode { get; set; } public Vector2 mousePosition { get; set; } public Vector2 delta { get; set; } public bool shift { get; set; } public bool control { get; set; } public bool alt { get; set; } public bool command { get; set; } public int button { get; set; } public int clickCount { get; set; } public string commandName { get; set; } public void Use() { } public bool isKey => false; public bool isMouse => false; public char character { get; set; } }
    public class GUIContent { public string text; public Texture image; public string tooltip; public GUIContent() { } public GUIContent(string t) { text = t; } public GUIContent(string t, string tip) { text = t; tooltip = tip; } public GUIContent(Texture i) { image = i; } public GUIContent(string t, Texture i) { text = t; image = i; } public GUIContent(string t, Texture i, string tip) { text = t; image = i; tooltip = tip; } public static GUIContent none => new GUIContent(); }
    public class GUIStyle { public TextAnchor alignment { get; set; } public int fontSize { get; set; } public FontStyle fontStyle { get; set; } public bool wordWrap { get; set; } public bool richText { get; set; } public GUIStyleState normal { get; set; } public GUIStyleState hover { get; set; } public GUIStyleState active { get; set; } public GUIStyleState focused { get; set; } public RectOffset padding { get; set; } public RectOffset margin { get; set; } public RectOffset border { get; set; } public RectOffset overflow { get; set; } public bool stretchWidth { get; set; } public bool stretchHeight { get; set; } public Vector2 CalcSize(GUIContent c) => default; public float CalcHeight(GUIContent c, float w) => 0; public void Draw(Rect r, GUIContent c, bool hover, bool active, bool on, bool focus) { } public static implicit operator GUIStyle(string s) => null; }
    public class GUIStyleState { public Color textColor { get; set; } public Texture2D background { get; set; } }
    public class RectOffset { public int left, right, top, bottom; public RectOffset() { } public RectOffset(int l, int r, int t, int b) { left = l; right = r; top = t; bottom = b; } }
    public class GUISkin : Object { public GUIStyle label { get; set; } public GUIStyle button { get; set; } public GUIStyle toggle { get; set; } public GUIStyle window { get; set; } public GUIStyle box { get; set; } public GUIStyle textField { get; set; } public GUIStyle textArea { get; set; } public GUIStyle horizontalSlider { get; set; } public GUIStyle horizontalSliderThumb { get; set; } public GUIStyle verticalSlider { get; set; } public GUIStyle verticalSliderThumb { get; set; } public GUIStyle scrollView { get; set; } }
    public class GUILayoutOption { }
    public static class GUI { public static Color color { get; set; } public static Color backgroundColor { get; set; } public static Color contentColor { get; set; } public static GUISkin skin { get; set; } public static bool enabled { get; set; } public static int depth { get; set; } public static string tooltip { get; set; } public static void Label(Rect r, string t) { } public static void Label(Rect r, string t, GUIStyle s) { } public static void Label(Rect r, GUIContent c) { } public static void Label(Rect r, GUIContent c, GUIStyle s) { } public static void Label(Rect r, Texture t) { } public static bool Button(Rect r, string t) => false; public static bool Button(Rect r, string t, GUIStyle s) => false; public static bool Button(Rect r, GUIContent c) => false; public static bool Button(Rect r, GUIContent c, GUIStyle s) => false; public static void Box(Rect r, string t) { } public static void Box(Rect r, string t, GUIStyle s) { } public static void DrawTexture(Rect r, Texture t) { } public static void DrawTexture(Rect r, Texture t, ScaleMode m) { } public static void DrawTextureWithTexCoords(Rect r, Texture t, Rect tc) { } public static string TextField(Rect r, string t) => ""; public static string TextField(Rect r, string t, GUIStyle s) => ""; public static string TextArea(Rect r, string t) => ""; public static float HorizontalSlider(Rect r, float v, float min, float max) => 0; public static bool Toggle(Rect r, bool v, string t) => false; public static bool Toggle(Rect r, bool v, string t, GUIStyle s) => false; public static bool Toggle(Rect r, bool v, GUIContent c, GUIStyle s) => false; public static void BeginGroup(Rect r) { } public static void BeginGroup(Rect r, GUIStyle s) { } public static void EndGroup() { } public static Vector2 BeginScrollView(Rect r, Vector2 sp, Rect vr) => default; public static Vector2 BeginScrollView(Rect r, Vector2 sp, Rect vr, bool ha, bool va) => default; public static void EndScrollView() { } public static void DragWindow() { } public static void DragWindow(Rect r) { } public static int SelectionGrid(Rect r, int s, string[] t, int c) => 0; public static int Toolbar(Rect r, int s, string[] t) => 0; public static void SetNextControlName(string n) { } public static string GetNameOfFocusedControl() => ""; public static void FocusControl(string n) { } public static void BeginClip(Rect r) { } public static void EndClip() { } public static Rect Window(int id, Rect r, WindowFunction f, string t) => default; public delegate void WindowFunction(int id); public static float VerticalSlider(Rect r, float v, float min, float max) => 0; }
    public static class GUILayout { public static void Label(string t, params GUILayoutOption[] o) { } public static void Label(GUIContent c, params GUILayoutOption[] o) { } public static void Label(GUIContent c, GUIStyle s, params GUILayoutOption[] o) { } public static bool Button(string t, params GUILayoutOption[] o) => false; public static bool Button(string t, GUIStyle s, params GUILayoutOption[] o) => false; public static void BeginHorizontal(params GUILayoutOption[] o) { } public static void EndHorizontal() { } public static void BeginVertical(params GUILayoutOption[] o) { } public static void EndVertical() { } public static void Space(float p) { } public static void FlexibleSpace() { } public static GUILayoutOption Width(float w) => null; public static GUILayoutOption Height(float h) => null; public static GUILayoutOption MinWidth(float w) => null; public static GUILayoutOption MaxWidth(float w) => null; public static GUILayoutOption MinHeight(float h) => null; public static GUILayoutOption MaxHeight(float h) => null; public static GUILayoutOption ExpandWidth(bool e) => null; public static GUILayoutOption ExpandHeight(bool e) => null; public static Vector2 BeginScrollView(Vector2 sp, params GUILayoutOption[] o) => default; public static void EndScrollView() { } public static string TextField(string t, params GUILayoutOption[] o) => ""; public static bool Toggle(bool v, string t, params GUILayoutOption[] o) => false; public static float HorizontalSlider(float v, float min, float max, params GUILayoutOption[] o) => 0; public static Rect Window(int id, Rect r, GUI.WindowFunction f, string t, params GUILayoutOption[] o) => default; }
    public static class GUIUtility { public static int hotControl { get; set; } public static void ExitGUI() { } public static int GetControlID(FocusType f) => 0; }
    public enum FocusType { Passive, Keyboard, Native }
    public static class Screen { public static int width => 0; public static int height => 0; }
    public static class Input { public static Vector3 mousePosition => default; public static bool GetMouseButton(int b) => false; public static bool GetMouseButtonDown(int b) => false; public static bool GetMouseButtonUp(int b) => false; public static bool GetKey(KeyCode k) => false; public static bool GetKeyDown(KeyCode k) => false; public static bool GetKeyUp(KeyCode k) => false; public static float GetAxis(string n) => 0; }
    public static class Time { public static float time => 0; public static float deltaTime => 0; public static float realtimeSinceStartup => 0; public static int frameCount => 0; }
    public static class Random { public static float value => 0; public static int Range(int min, int max) => 0; public static float Range(float min, float max) => 0; }
    public static class SystemInfo { public static int systemMemorySize => 0; public static string operatingSystem => ""; }
    public static class GL { public static void PushMatrix() { } public static void PopMatrix() { } public static void LoadPixelMatrix() { } public static void Begin(int mode) { } public static void End() { } public static void Color(Color c) { } public static void Vertex3(float x, float y, float z) { } public static void TexCoord2(float u, float v) { } public const int QUADS = 7; public const int TRIANGLES = 4; public const int LINES = 1; }
    public static class Resources { public static T Load<T>(string p) where T : Object => null; public static T[] FindObjectsOfTypeAll<T>() where T : Object => null; }
    public static class PlayerPrefs { public static void SetInt(string k, int v) { } public static int GetInt(string k, int d = 0) => d; public static void SetFloat(string k, float v) { } public static float GetFloat(string k, float d = 0) => d; public static void SetString(string k, string v) { } public static string GetString(string k, string d = "") => d; public static bool HasKey(string k) => false; public static void DeleteKey(string k) { } public static void Save() { } }
    public class AnimationCurve { public AnimationCurve(params Keyframe[] keys) { } public float Evaluate(float t) => 0; public Keyframe[] keys { get; set; } }
    public struct Keyframe { public float time; public float value; public Keyframe(float t, float v) { time = t; value = v; } }
    public struct Matrix4x4 { public static Matrix4x4 identity => default; }
    public class GenericMenu { public void AddItem(GUIContent c, bool on, MenuFunction f) { } public void AddDisabledItem(GUIContent c) { } public void AddSeparator(string p) { } public void DropDown(Rect r) { } public void ShowAsContext() { } public delegate void MenuFunction(); public void AddItem(GUIContent c, bool on, MenuFunction2 f, object d) { } public delegate void MenuFunction2(object d); }
    public enum FilterMode { Point, Bilinear, Trilinear }
    public enum TextClipping { Overflow, Clip }
    public enum ImagePosition { ImageLeft, ImageAbove, ImageOnly, TextOnly }
    public class GUIClip { }
    public class AudioClip : Object { }
    public class AudioSource : Behaviour { }
    public sealed class Quaternion { public static Quaternion identity => default; }
    public class Mesh : Object { }
    public struct Bounds { }
    public class Font : Object { }
    public class TextAsset : Object { public string text => ""; public byte[] bytes => null; }
    public struct LayerMask { }
    public struct RaycastHit { }
    public struct Ray { }
    public class Physics : Object { }
    public class Collider : Component { }
    public class BoxCollider : Collider { }
    public class RectTransform : Transform { }
}
